language: node_js
node_js:
  - "stable"
install:
  - npm install
services:
  - postgresql
cache:
  directories:
    - "node_modules"
env:
  global:
  - NODE_ENV=test

before_script:
  - psql -c 'create database dac_db_test;' -U postgres
script:
  - npm test
after_success:
  - npm run coverage